Automate application deployment and other things
konveyor/crane-ui-tests pull request #13
Opened 2021-11-01 05:44 UTC by nachandr

1)Application deployment on source cluster
2)On source cluster, verify that application is running before migration
3)On target cluster, verify that application is running after migration

2021-11-23 07:06 UTC, nitishSr commented on cypress/integration/tests/indirect_migration_using_S3.test.ts
> +import { login, setup_source_cluster, cleanup_source_cluster, post_migration_verification } from '../../utils/utils';
wrong import - "post_migration_verification_on_target"

2021-11-23 07:07 UTC, nitishSr commented on cypress/integration/tests/indirect_migration_using_S3.test.ts
> +      setup_source_cluster();
Can we have it in before() hook

2021-11-23 07:07 UTC, nitishSr commented on cypress/integration/tests/indirect_migration_using_S3.test.ts
> +      post_migration_verification();
These two can be moved to after() hook

2021-11-23 07:08 UTC, nitishSr requested changes
Can we also have same changes of calling setup_cluster, cleanup cluster methods in migration_pipeline_status_test

2021-12-01 05:59 UTC, nachandr commented
All the enhancements were merged through https://github.com/konveyor/crane-ui-tests/pull/14 . So, closing this PR.

2021-12-01 05:59 UTC, closed without merging